require('./modules/login/module')
require('./apiLocations')
require('./modules/gumgatagdefinition/module')
require('./modules/gumgacustomfield/module')
require('./modules/pessoa/module')
require('./modules/colaborador/module')
require('./modules/fornecedor/module')
require('./modules/viagem/module')
require('./modules/rota/module')
require('./modules/movimento/module')
require('./modules/destino/module')
require('./modules/base/module')
require('./modules/welcome/module')
require('./modules/studio/module')
// FIMREQUIRE